channels:
  - conda-forge
dependencies:
  # make sure python version is correct
  - python=3.10
  - numba=0.54.1
  - numpy=1.20.3
  - pandas=1.3.4
  - scikit-learn=0.24.2
  - scipy=1.7.1
  - alembic=1.7.4
  - sqlalchemy=1.4.26
  - sqlalchemy-utils=0.38.2
  - anytree=2.8.0
  - psycopg2=2.9.3
  - pywin32=301
  - pyyaml=6.0
  - bs4=0.0.1
  - streamlit==1.25.0

  # some io monitoring tools
  - memory-profiler=0.60.0

  # possibly not required anymore
  - requests=2.26.0
  - pytables=3.6.1

  # django
  - django=4.1.2
  - djangorestframework=3.14.0

  # http server
  -
