channels:
  - conda-forge
dependencies:
  # testing
  - pytest=6.2.5
  - pytest-mock=3.6.1
  - pytest-asyncio=0.18.1
  - pytest-cov=3.0.0
  - psycopg=3.0.9  # required by pytest-postgresql. can be used in parallel with psycopg2

  # code checks
  - black=22.3.0
  - flake8=4.0.1
  - flake8-bugbear=21.9.2  # used by flake8 to find likely bugs
  - flake8-comprehensions=3.7.0  # used by flake8 for linting of unnecessary comprehensions
  - isort=5.9.3
  - mypy=0.910
  - pre-commit=2.15.0
  - pycodestyle=2.8.0  # used by flake
  - pyupgrade=2.29.0
  - types-python-dateutil=2.8.2  # used by mypy

  # other
  - matplotlib=3.4.3
  - openpyxl=3.0.9
  - seaborn=0.11.2
  - toml=0.10.2

  # pip dependencies
  - pip=21.3
  - pip:
    - pytest-postgresql==4.1.0
    - yesqa==1.3.0
