# Generated by Django 4.2.2 on 2023-07-04 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("playground", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="geeksmodel",
            options={"ordering": ["title"]},
        ),
    ]
