"""create_model_setting_tables

Revision ID: cb83f9512be7
Revises: 1dc13c8837c9
Create Date: 2023-07-03 22:58:29.658606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb83f9512be7'
down_revision = '1dc13c8837c9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_setting',
    sa.Column('model_version_id', sa.String(length=2048), nullable=False),
    sa.Column('display_name', sa.String(length=2048), nullable=False),
    sa.Column('decay_constant', sa.Float(), server_default='0.015', nullable=True),
    sa.Column('factor_selection_method', sa.String(length=2048), server_default='method1', nullable=False),
    sa.ForeignKeyConstraint(['model_version_id'], ['models.model_version_id'], ),
    sa.PrimaryKeyConstraint('model_version_id'),
    sa.UniqueConstraint('model_version_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('model_setting')
    # ### end Alembic commands ###
